// Snyc with NextConfigJS

export const ALLOWED_IMAGE_DOMAINS = [
  "assets-jane-cac1-20.janeapp.net",
  "assets-jane-cac1-21.janeapp.net",
  "www.peak-resilience.com",
  "assets-jane-cac1-22.janeapp.net",
  "assets-jane-cac1-23.janeapp.net",
  "assets-jane-cac1-24.janeapp.net",
  "randomuser.me",
  "images.unsplash.com",
  "thrivedowntown.com",
  "static.wixstatic.com",
  "openspacecounselling.ca",
  "skylarkclinic.ca",
  "lotustherapy.ca",
  "blueskywellnessclinic.ca",
  "www.blueskywellnessclinic.ca",
  "ayoua.com",
  "eastvancouvercounselling.ca",
  "arccounselling.ca",
  "clearheartcounselling.com",
  "gatherandground.ca",
  "chromacounselling.ca",
  "wellspringcounselling.ca",
  "fieldworkcounselling.ca",
  "freemindtherapy.ca",
  "providencetherapybc.com",
  "vancouvercounsellingclinic.ca",
  "jerichocounselling.com",
  "benchmarkcounselling.com",
  "richmondcounselling.com",
  "panoramawellness.ca",
  "cdn.prod.website-files.com",
  "abbotsford.skylarkclinic.ca",
  "cdn-hhfkf.nitrocdn.com",
  "images.squarespace-cdn.com",
  "repiphany.com",
  "vancouvercounsellingclinic.com",
  "hippo-ai-public-assets.s3.us-east-1.amazonaws.com",
  "mlddlxmupu0y.i.optimole.com",
] as const;
