-- First insert the therapist
-- WITH inserted_therapist AS (
--   INSERT INTO therapists (
--     first_name,
--     last_name,
--     gender,
--     pronouns,
--     profile_img_url,
--     video_intro_link,
--     ai_summary,
--     clinic_profile_url,
--     clinic_booking_url,
--     therapist_email,
--     clinic_name,
--     clinic_street,
--     clinic_city,
--     clinic_province,
--     clinic_postal_code,
--     clinic_country,
--     availability,
--     education,
--     certifications,
--     approaches,
--     areas_of_focus,
--     languages,
--     licenses,
--     bio
--   ) VALUES (
--     'Laura',
--     'Langen',
--     'female',
--     'she/her',
--     'https://www.peak-resilience.com/wp-content/uploads/2024/02/IMG_2916-1024x678.jpg',
--     'https://www.youtube.com/watch?v=3fxY_qyl1Oo',
--     'Laura Langen is a Registered Clinical Counsellor (RCC) specializing in trauma-informed therapy, relationship counseling, and mental health support. With a unique background in business and personal experience with mental health challenges, she offers both individual and relationship therapy through various modalities including ACT, somatic experiencing, and the Gottman Method.',
--     'https://www.peak-resilience.com/laura-langen/',
--     NULL,
--     'hello@elementaltherapy.ca',
--     'Peak Resilience',
--     '1111 Melville St #589',
--     'Vancouver',
--     'BC',
--     'V6E 3V6',
--     'CA',
--     'both',
--     ARRAY['Business Degree'],
--     ARRAY['Crime Victim Assistance Program (CVAP) Approved'],
--     jsonb_build_object(
--       'long_term', ARRAY[
--         'Acceptance and Commitment Therapy (ACT)',
--         'Trauma Informed Therapy',
--         'Somatic Experiencing + Sensorimotor Therapy',
--         'Intersectional Feminist Therapy',
--         'Solution Focused Therapy',
--         'Internal Family Systems Therapy- Parts Work',
--         'Nature Based Therapy',
--         'Cognitive Behavioural Therapy (CBT)',
--         'Eye Movement Desensitization and Reprocessing (EMDR)',
--         'Psychoeducation',
--         'Gottman Method'
--       ]
--     ),
--     ARRAY[
--       'Anxiety', 'Boundary Setting', 'Break-Ups', 'Burnout', 'Career', 
--       'Childhood Trauma', 'Communication Skills', 'Dating', 'Depersonalization',
--       'Dissociation', 'Emotional Regulation and Anger', 'Family Conflict',
--       'Goal Setting', 'Grief and Loss', 'Identity', 'Interpersonal Challenges',
--       'Kink and Sex Positive', 'Leadership Development', 'Life Meaning and Purpose',
--       'Life Transitions', 'Motivation', 'Nervous System Regulation', 'Perfectionism',
--       'PTSD / Complex PTSD', 'Relational Trauma', 'Relationship Issues',
--       'Self Worth and Personal Growth', 'Self-Esteem', 'Sex Therapy',
--       'Sexual Trauma', 'Sexual Violence', 'Stress Management and Stress Reduction',
--       'Trauma'
--     ],
--     ARRAY['English'],
--     ARRAY[jsonb_build_object(
--       'license_number', '20480',
--       'state', 'BC',
--       'type', 'Registered Clinical Counsellor',
--       'organization', 'BCACC'
--     )],
--     'Hi! My name is Laura and I am an RCC at Peak. I was born and raised in Saskatoon where I completed my business degree which supported me in my years of leadership and business development with value aligned companies. Although I loved my work, my personal experiences with mental health and witnessing the need for quality mental health care led me to go back to school and dedicate my career to mental health. I personally have gone through my own mental health challenges and know what it is like to be in the dark and thinking things will not get better. I am here to tell you they can and although life can be hard, it can be really beautiful too.

-- If you are looking for a therapist that not only helps you with insight but supports you with positive change and taking action to improve your life, I may be a great fit. My approach works with both mind and body through a client centered, trauma informed, and anti-oppressive lens. I offer both individual and relationship therapy and virtually, in person, and outdoors in nature-based sessions. I regularly integrate acceptance and commitment therapy (ACT) that focuses on working with our emotions and not against them. Somatic, body-based approaches are also a key element of my work as I believe there is deep wisdom in our bodies that cannot always be accessed by cognitive approaches alone. As a relationship therapist, my primary modality is Gottman Method with an aim to create shared meaning and understanding while managing emotions and conflict.

-- I know seeking support can bring up many emotions and I place my first priority on developing an authentic, trusting, and safe relationship with each other. I recognize no two humans are alike and we will work together to customize your therapy as we work together. I believe therapy should move between the dark tough times and the light celebratory times, and I integrate compassion, values-based work, and humour along the way in our process. Know you are not alone in what you are here for, and I look forward to meeting you and walking alongside you at this time in your life.'
--   ) RETURNING id
-- )
-- -- Then insert some sample fees
-- INSERT INTO therapist_fees (
--   therapist_id,
--   session_category,
--   session_type,
--   delivery_method,
--   duration_minutes,
--   price,
--   currency
-- ) 
-- SELECT 
--   id,
--   session_category,
--   session_type,
--   delivery_method,
--   duration_minutes,
--   price,
--   currency
-- FROM inserted_therapist,
-- (VALUES 
--   ('initial'::session_category_type, 'individual'::session_type_type, 'in_person'::delivery_method_type, 50, 150.00, 'CAD'),
--   ('subsequent'::session_category_type, 'individual'::session_type_type, 'in_person'::delivery_method_type, 50, 130.00, 'CAD'),
--   ('initial'::session_category_type, 'couples'::session_type_type, 'in_person'::delivery_method_type, 80, 180.00, 'CAD'),
--   ('subsequent'::session_category_type, 'couples'::session_type_type, 'in_person'::delivery_method_type, 80, 160.00, 'CAD')
-- ) AS fees(
--   session_category,
--   session_type,
--   delivery_method,
--   duration_minutes,
--   price,
--   currency
-- );