-- ------------------------------------------------------------------
--  SRP-001  •  Core tables for Lotus AI-Therapist prototype
-- ------------------------------------------------------------------

create extension if not exists pgcrypto;          -- for gen_random_uuid()

-- -------------------------------------------------  lotus_sessions
create table public.lotus_sessions (
    id          uuid primary key default gen_random_uuid(),
    stage       text      not null default 'S1',        -- S1 … S4
    context     jsonb     not null default '{}'::jsonb, -- optional notes
    started_at  timestamptz not null default now(),
    ended_at    timestamptz
);

create index lotus_sessions_started_idx
  on public.lotus_sessions(started_at desc);

-- -------------------------------------------------  lotus_messages
create table public.lotus_messages (
    id              bigint generated by default as identity primary key,
    session_id      uuid not null
                    references public.lotus_sessions(id) on delete cascade,
    sender          text not null check (sender in ('user','bot')),
    body            text not null,           -- what the UI displays
    llm_payload     jsonb,                   -- full LLM response incl. “thoughts”
    created_at      timestamptz not null default now()
);

create index lotus_messages_session_time_idx
  on public.lotus_messages(session_id, created_at desc);
